version: '3.5'

services:
  app-name:
    build: "."
    # image: USER/NAME:latest
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "80:80"
    restart: always

  postgres:
    image: postgres:12.6-alpine
    env_file: .env
    volumes:
      - ./db:/var/lib/postgres/data
    restart: always
