version: '3.5'

services:
  NAME:
    build: "."
    image: USER/NAME:testing
    environment:
      - SESSION_SECRET=${SESSION_SECRET:-CHANGEME}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - ENABLE_CONSOLE=${ENABLE_CONSOLE:-false}
    depends_on:
      - postgres
    ports:
      - "8000:80"
    restart: unless-stopped

  postgres:
    image: postgres-12.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    restart: unless-stopped
